# Pandas DataFrame

In [1]:
import pandas as pd
data = pd.read_csv('data/gapminder_gdp_europe.csv', index_col="country")

In [6]:
data.head()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820

In [3]:
data.tail()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Spain,3834.034742,4564.802410,5693.843879,7993.512294,10638.75131,13236.921170,13926.169970,15764.983130,18603.064520,20445.298960,24835.471660,28821.063700
Sweden,8527.844662,9911.878226,12329.441920,15258.296970,17832.02464,18855.725210,20667.381250,23586.929270,23880.016830,25266.594990,29341.630930,33859.748350
Switzerland,14734.232750,17909.489730,20431.092700,22966.144320,27195.11304,26982.290520,28397.715120,30281.704590,31871.530300,32135.323010,34480.957710,37506.419070
Turkey,1969.100980,2218.754257,2322.869908,2826.356387,3450.69638,4269.122326,4241.356344,5089.043686,5678.348271,6601.429915,6508.085718,8458.276384
United Kingdom,9979.508487,11283.177950,12477.177070,14142.850890,15895.11641,17428.748460,18232.424520,21664.787670,22705.092540,26074.531360,29478.999190,33203.261280

In [8]:
data.iloc[0,0]

1601.056136

In [9]:
data.loc['Belgium', 'gdpPercap_1957']

9714.960623

In [10]:
data.loc['Belgium']

gdpPercap_1952     8343.105127
gdpPercap_1957     9714.960623
gdpPercap_1962    10991.206760
gdpPercap_1967    13149.041190
gdpPercap_1972    16672.143560
gdpPercap_1977    19117.974480
gdpPercap_1982    20979.845890
gdpPercap_1987    22525.563080
gdpPercap_1992    25575.570690
gdpPercap_1997    27561.196630
gdpPercap_2002    30485.883750
gdpPercap_2007    33692.605080
Name: Belgium, dtype: float64

In [11]:
data.loc['Belgium',:]

gdpPercap_1952     8343.105127
gdpPercap_1957     9714.960623
gdpPercap_1962    10991.206760
gdpPercap_1967    13149.041190
gdpPercap_1972    16672.143560
gdpPercap_1977    19117.974480
gdpPercap_1982    20979.845890
gdpPercap_1987    22525.563080
gdpPercap_1992    25575.570690
gdpPercap_1997    27561.196630
gdpPercap_2002    30485.883750
gdpPercap_2007    33692.605080
Name: Belgium, dtype: float64

In [14]:
data.loc[['Belgium','Switzerland'],:]

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Belgium,8343.105127,9714.960623,10991.20676,13149.04119,16672.14356,19117.97448,20979.84589,22525.56308,25575.57069,27561.19663,30485.88375,33692.60508
Switzerland,14734.232750,17909.489730,20431.09270,22966.14432,27195.11304,26982.29052,28397.71512,30281.70459,31871.53030,32135.32301,34480.95771,37506.41907

In [16]:
data.loc[['Belgium','Switzerland'],:].T.corr()

country       Belgium  Switzerland
country
Belgium      1.000000     0.976492
Switzerland  0.976492     1.000000

In [18]:
data.loc[:,'gdpPercap_1987':'gdpPercap_2002'].head()

,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002
country,,,,
Albania,3738.932735,2497.437901,3193.054604,4604.211737
Austria,23687.826070,27042.018680,29095.920660,32417.607690
Belgium,22525.563080,25575.570690,27561.196630,30485.883750
Bosnia and Herzegovina,4314.114757,2546.781445,4766.355904,6018.975239
Bulgaria,8239.854824,6302.623438,5970.388760,7696.777725

In [19]:
data.loc[:,'gdpPercap_1987':'gdpPercap_2002'].mean()

gdpPercap_1987    17214.310727
gdpPercap_1992    17061.568084
gdpPercap_1997    19076.781802
gdpPercap_2002    21711.732422
dtype: float64

In [23]:
data.loc[:,'gdpPercap_1987':'gdpPercap_2002'].T.mean()

country
Albania                    3508.409244
Austria                   28060.843275
Belgium                   26537.053538
Bosnia and Herzegovina     4411.556836
Bulgaria                   7052.411187
Croatia                   10943.593070
Czech Republic            16063.047270
Denmark                   28373.440347
Finland                   23429.179498
France                    25396.513875
Germany                   27242.293743
Greece                    18730.994418
Hungary                   12519.705222
Iceland                   27822.974978
Ireland                   22507.669647
Italy                     23466.000577
Montenegro                 7939.664209
Netherlands               28603.290408
Norway                    37868.443882
Poland                     9745.763795
Portugal                  16714.628705
Romania                    7881.647709
Serbia                    10086.585576
Slovak Republic           11825.186081
Slovenia                  17678.594610
Spain                     19912.204568
Sweden                    25518.793005
Switzerland               32192.378903
Turkey                     5969.226898
United Kingdom            24980.852690
dtype: float64

In [25]:
data.iloc[:,0:3]

                        gdpPercap_1952  gdpPercap_1957  gdpPercap_1962
country
Albania                    1601.056136     1942.284244     2312.888958
Austria                    6137.076492     8842.598030    10750.721110
Belgium                    8343.105127     9714.960623    10991.206760
Bosnia and Herzegovina      973.533195     1353.989176     1709.683679
Bulgaria                   2444.286648     3008.670727     4254.337839
Croatia                    3119.236520     4338.231617     5477.890018
Czech Republic             6876.140250     8256.343918    10136.867130
Denmark                    9692.385245    11099.659350    13583.313510
Finland                    6424.519071     7545.415386     9371.842561
France                     7029.809327     8662.834898    10560.485530
Germany                    7144.114393    10187.826650    12902.462910
Greece                     3530.690067     4916.299889     6017.190733
Hungary                    5263.673816     6040.180011     7550.359877
Iceland                    7267.688428     9244.001412    10350.159060
Ireland                    5210.280328     5599.077872     6631.597314
Italy                      4931.404155     6248.656232     8243.582340
Montenegro                 2647.585601     3682.259903     4649.593785
Netherlands                8941.571858    11276.193440    12790.849560
Norway                    10095.421720    11653.973040    13450.401510
Poland                     4029.329699     4734.253019     5338.752143
Portugal                   3068.319867     3774.571743     4727.954889
Romania                    3144.613186     3943.370225     4734.997586
Serbia                     3581.459448     4981.090891     6289.629157
Slovak Republic            5074.659104     6093.262980     7481.107598
Slovenia                   4215.041741     5862.276629     7402.303395
Spain                      3834.034742     4564.802410     5693.843879
Sweden                     8527.844662     9911.878226    12329.441920
Switzerland               14734.232750    17909.489730    20431.092700
Turkey                     1969.100980     2218.754257     2322.869908
United Kingdom             9979.508487    11283.177950    12477.177070

In [26]:
subset =data.loc[:,'gdpPercap_1987':'gdpPercap_2002']
print('where are the values large', subset>10000)

where are the values large                         gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  \
country
Albania                          False           False           False
Austria                           True            True            True
Belgium                           True            True            True
Bosnia and Herzegovina           False           False           False
Bulgaria                         False           False           False
Croatia                           True           False           False
Czech Republic                    True            True            True
Denmark                           True            True            True
Finland                           True            True            True
France                            True            True            True
Germany                           True            True            True
Greece                            True            True            True
Hungary                           True            True            True
Iceland                           True            True            True
Ireland                           True            True            True
Italy                             True            True            True
Montenegro                        True           False           False
Netherlands                       True            True            True
Norway                            True            True            True
Poland                           False           False            True
Portugal                          True            True            True
Romania                          False           False           False
Serbia                            True           False           False
Slovak Republic                   True           False            True
Slovenia                          True            True            True
Spain                             True            True            True
Sweden                            True            True            True
Switzerland                       True            True            True
Turkey                           False           False           False
United Kingdom                    True            True            True

                        gdpPercap_2002
country
Albania                          False
Austria                           True
Belgium                           True
Bosnia and Herzegovina           False
Bulgaria                         False
Croatia                           True
Czech Republic                    True
Denmark                           True
Finland                           True
France                            True
Germany                           True
Greece                            True
Hungary                           True
Iceland                           True
Ireland                           True
Italy                             True
Montenegro                       False
Netherlands                       True
Norway                            True
Poland                            True
Portugal                          True
Romania                          False
Serbia                           False
Slovak Republic                   True
Slovenia                          True
Spain                             True
Sweden                            True
Switzerland                       True
Turkey                           False
United Kingdom                    True

In [27]:
subset>10000

,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002
country,,,,
Albania,False,False,False,False
Austria,True,True,True,True
Belgium,True,True,True,True
Bosnia and Herzegovina,False,False,False,False
Bulgaria,False,False,False,False
Croatia,True,False,False,True
Czech Republic,True,True,True,True
Denmark,True,True,True,True
Finland,True,True,True,True
France,True,True,True,True
Germany,True,True,True,True
Greece,True,True,True,True
Hungary,True,True,True,True
Iceland,True,True,True,True
Ireland,True,True,True,True
Italy,True,True,True,True
Montenegro,True,False,False,False
Netherlands,True,True,True,True
Norway,True,True,True,True
Poland,False,False,True,True
Portugal,True,True,True,True
Romania,False,False,False,False
Serbia,True,False,False,False
Slovak Republic,True,False,True,True
Slovenia,True,True,True,True
Spain,True,True,True,True
Sweden,True,True,True,True
Switzerland,True,True,True,True
Turkey,False,False,False,False
United Kingdom,True,True,True,True

In [28]:
mask = subset> 10000
mask.head()

,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002
country,,,,
Albania,False,False,False,False
Austria,True,True,True,True
Belgium,True,True,True,True
Bosnia and Herzegovina,False,False,False,False
Bulgaria,False,False,False,False

In [29]:
subset[mask]

,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002
country,,,,
Albania,NaN,NaN,NaN,NaN
Austria,23687.82607,27042.01868,29095.92066,32417.60769
Belgium,22525.56308,25575.57069,27561.19663,30485.88375
Bosnia and Herzegovina,NaN,NaN,NaN,NaN
Bulgaria,NaN,NaN,NaN,NaN
Croatia,13822.58394,NaN,NaN,11628.38895
Czech Republic,16310.44340,14297.02122,16048.51424,17596.21022
Denmark,25116.17581,26406.73985,29804.34567,32166.50006
Finland,21141.01223,20647.16499,23723.95020,28204.59057
France,22066.44214,24703.79615,25889.78487,28926.03234
Germany,24639.18566,26505.30317,27788.88416,30035.80198
Greece,16120.52839,17541.49634,18747.69814,22514.25480
Hungary,12986.47998,10535.62855,11712.77680,14843.93556
Iceland,26923.20628,25144.39201,28061.09966,31163.20196
Ireland,13872.86652,17558.81555,24521.94713,34077.04939
Italy,19207.23482,22013.64486,24675.02446,27968.09817
Montenegro,11732.51017,NaN,NaN,NaN
Netherlands,23651.32361,26790.94961,30246.13063,33724.75778
Norway,31540.97480,33965.66115,41283.16433,44683.97525
Poland,NaN,NaN,10159.58368,12002.23908
Portugal,13039.30876,16207.26663,17641.03156,19970.90787
Romania,NaN,NaN,NaN,NaN
Serbia,15870.87851,NaN,NaN,NaN
Slovak Republic,12037.26758,NaN,12126.23065,13638.77837
Slovenia,18678.53492,14214.71681,17161.10735,20660.01936
Spain,15764.98313,18603.06452,20445.29896,24835.47166
Sweden,23586.92927,23880.01683,25266.59499,29341.63093
Switzerland,30281.70459,31871.53030,32135.32301,34480.95771
Turkey,NaN,NaN,NaN,NaN
United Kingdom,21664.78767,22705.09254,26074.53136,29478.99919

In [35]:
mask_higher = data.apply(lambda x: x>x.mean(),axis=0)
mask_higher.head()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Albania,False,False,False,False,False,False,False,False,False,False,False,False
Austria,True,True,True,True,True,True,True,True,True,True,True,True
Belgium,True,True,True,True,True,True,True,True,True,True,True,True
Bosnia and Herzegovina,False,False,False,False,False,False,False,False,False,False,False,False
Bulgaria,False,False,False,False,False,False,False,False,False,False,False,False

In [31]:
data[mask_higher]

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Austria,6137.076492,8842.598030,10750.721110,12834.60240,16661.62560,19749.42230,21597.08362,23687.82607,27042.01868,29095.92066,32417.60769,36126.49270
Belgium,8343.105127,9714.960623,10991.206760,13149.04119,16672.14356,19117.97448,20979.84589,22525.56308,25575.57069,27561.19663,30485.88375,33692.60508
Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Croatia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Czech Republic,6876.140250,8256.343918,10136.867130,11399.44489,13108.45360,14800.16062,NaN,NaN,NaN,NaN,NaN,NaN
Denmark,9692.385245,11099.659350,13583.313510,15937.21123,18866.20721,20422.90150,21688.04048,25116.17581,26406.73985,29804.34567,32166.50006,35278.41874
Finland,6424.519071,7545.415386,9371.842561,10921.63626,14358.87590,15605.42283,18533.15761,21141.01223,20647.16499,23723.95020,28204.59057,33207.08440
France,7029.809327,8662.834898,10560.485530,12999.91766,16107.19171,18292.63514,20293.89746,22066.44214,24703.79615,25889.78487,28926.03234,30470.01670
Germany,7144.114393,10187.826650,12902.462910,14745.62561,18016.18027,20512.92123,22031.53274,24639.18566,26505.30317,27788.88416,30035.80198,32170.37442
Greece,NaN,NaN,NaN,NaN,12724.82957,NaN,NaN,NaN,17541.49634,NaN,22514.25480,27538.41188
Hungary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Iceland,7267.688428,9244.001412,10350.159060,13319.89568,15798.06362,19654.96247,23269.60750,26923.20628,25144.39201,28061.09966,31163.20196,36180.78919
Ireland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17558.81555,24521.94713,34077.04939,40675.99635
Italy,NaN,NaN,NaN,NaN,NaN,NaN,16537.48350,19207.23482,22013.64486,24675.02446,27968.09817,28569.71970
Montenegro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Netherlands,8941.571858,11276.193440,12790.849560,15363.25136,18794.74567,21209.05920,21399.46046,23651.32361,26790.94961,30246.13063,33724.75778,36797.93332
Norway,10095.421720,11653.973040,13450.401510,16361.87647,18965.05551,23311.34939,26298.63531,31540.97480,33965.66115,41283.16433,44683.97525,49357.19017
Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Portugal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Romania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Slovak Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Slovenia,NaN,NaN,NaN,NaN,NaN,15277.03017,17866.72175,18678.53492,NaN,NaN,NaN,25768.25759
Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18603.06452,20445.29896,24835.47166,28821.06370
Sweden,8527.844662,9911.878226,12329.441920,15258.29697,17832.02464,18855.72521,20667.38125,23586.92927,23880.01683,25266.59499,29341.63093,33859.74835
Switzerland,14734.232750,17909.489730,20431.092700,22966.14432,27195.11304,26982.29052,28397.71512,30281.70459,31871.53030,32135.32301,34480.95771,37506.41907
Turkey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United Kingdom,9979.508487,11283.177950,12477.177070,14142.85089,15895.11641,17428.74846,18232.42452,21664.78767,22705.09254,26074.53136,29478.99919,33203.26128

In [32]:
help(data.apply)

Help on method apply in module pandas.core.frame:

apply(func, axis=0, broadcast=False, raw=False, reduce=None, args=(), **kwds) method of pandas.core.frame.DataFrame instance
    Applies function along input axis of DataFrame.

    Objects passed to functions are Series objects having index
    either the DataFrame's index (axis=0) or the columns (axis=1).
    Return type depends on whether passed function aggregates, or the
    reduce argument if the DataFrame is empty.

    Parameters
    ----------
    func : function
        Function to apply to each column/row
    axis : {0 or 'index', 1 or 'columns'}, default 0
        * 0 or 'index': apply function to each column
        * 1 or 'columns': apply function to each row
    broadcast : boolean, default False
        For aggregation functions, return object of same size with values
        propagated
    raw : boolean, default False
        If False, convert each row or column into a Series. If raw=True the
        passed function will receive ndarray objects instead. If you are
        just applying a NumPy reduction function this will achieve much
        better performance
    reduce : boolean or None, default None
        Try to apply reduction procedures. If the DataFrame is empty,
        apply will use reduce to determine whether the result should be a
        Series or a DataFrame. If reduce is None (the default), apply's
        return value will be guessed by calling func an empty Series (note:
        while guessing, exceptions raised by func will be ignored). If
        reduce is True a Series will always be returned, and if False a
        DataFrame will always be returned.
    args : tuple
        Positional arguments to pass to function in addition to the
        array/series
    Additional keyword arguments will be passed as keywords to the function

    Notes
    -----
    In the current implementation apply calls func twice on the
    first column/row to decide whether it can take a fast or slow
    code path. This can lead to unexpected behavior if func has
    side-effects, as they will take effect twice for the first
    column/row.

    Examples
    --------
    >>> df.apply(numpy.sqrt) # returns DataFrame
    >>> df.apply(numpy.sum, axis=0) # equiv to df.sum(0)
    >>> df.apply(numpy.sum, axis=1) # equiv to df.sum(1)

    See also
    --------
    DataFrame.applymap: For elementwise operations
    DataFrame.aggregate: only perform aggregating type operations
    DataFrame.transform: only perform transformating type operations

    Returns
    -------
    applied : Series or DataFrame

In [38]:
wealth_score = mask_higher.aggregate('sum',axis=1)/len(data.columns)
wealth_score.head()

country
Albania                   0.0
Austria                   1.0
Belgium                   1.0
Bosnia and Herzegovina    0.0
Bulgaria                  0.0
dtype: float64

In [39]:
data.groupby(wealth_score).sum().head()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0.000000,36916.854200,46110.918793,56850.065437,71324.848786,88569.346898,104459.358438,113553.768507,119649.599409,92380.047256,103772.937598,118590.929863,149577.357928
0.333333,16790.046878,20942.456800,25744.935321,33567.667670,45277.839976,53860.456750,59679.634020,64436.912960,67918.093220,80876.051580,102086.795210,122803.729520
0.500000,11807.544405,14505.000150,18380.449470,21421.846200,25377.727380,29056.145370,31914.712050,35517.678220,36310.666080,40723.538700,45564.308390,51403.028210
1.000000,104317.277560,127332.008735,149989.154201,178000.350040,215162.343140,241143.412730,263388.781960,296825.131210,315238.235970,346930.926170,385109.939210,427850.333420

In [40]:
mask_higher.mean(axis=1).head()

country
Albania                   0.0
Austria                   1.0
Belgium                   1.0
Bosnia and Herzegovina    0.0
Bulgaria                  0.0
dtype: float64

In [42]:
help(mask_higher.aggregate)

Help on method aggregate in module pandas.core.frame:

aggregate(func, axis=0, *args, **kwargs) method of pandas.core.frame.DataFrame instance
    Aggregate using callable, string, dict, or list of string/callables

    .. versionadded:: 0.20.0

    Parameters
    ----------
    func : callable, string, dictionary, or list of string/callables
        Function to use for aggregating the data. If a function, must either
        work when passed a DataFrame or when passed to DataFrame.apply. For
        a DataFrame, can pass a dict, if the keys are DataFrame column names.

        Accepted Combinations are:

        - string function name
        - function
        - list of functions
        - dict of column names -> functions (or list of functions)

    Notes
    -----
    Numpy functions mean/median/prod/sum/std/var are special cased so the
    default behavior is applying the function along axis=0
    (e.g., np.mean(arr_2d, axis=0)) as opposed to
    mimicking the default Numpy behavior (e.g., np.mean(arr_2d)).

    `agg` is an alias for `aggregate`. Use the alias.

    Returns
    -------
    aggregated : DataFrame

    Examples
    --------

    >>> df = pd.DataFrame(np.random.randn(10, 3), columns=['A', 'B', 'C'],
    ...                   index=pd.date_range('1/1/2000', periods=10))
    >>> df.iloc[3:7] = np.nan

    Aggregate these functions across all columns

    >>> df.agg(['sum', 'min'])
                A         B         C
    sum -0.182253 -0.614014 -2.909534
    min -1.916563 -1.460076 -1.568297

    Different aggregations per column

    >>> df.agg({'A' : ['sum', 'min'], 'B' : ['min', 'max']})
                A         B
    max       NaN  1.514318
    min -1.916563 -1.460076
    sum -0.182253       NaN

    See also
    --------
    pandas.DataFrame.apply
    pandas.DataFrame.transform
    pandas.DataFrame.groupby.aggregate
    pandas.DataFrame.resample.aggregate
    pandas.DataFrame.rolling.aggregate

In [ ]:
# %load code/ex_dataframe

In [ ]:
## DataFrames Excercise 1

## DataFrames Excercise 1
 Write an expression to find the Per Capita GDP of Serbia in 2007.

In [45]:
data.loc['Serbia','gdpPercap_2007']

9786.534714

## DataFrames Excercise 2: DataFrame slicing
1. Do the two statements below produce the same output?
1. Based on this, what rule governs what is included (or not) in numerical slices and named slices in Pandas?

In [46]:
print(data.iloc[0:2, 0:2])
print(data.loc['Albania':'Belgium', 'gdpPercap_1952':'gdpPercap_1962'])

         gdpPercap_1952  gdpPercap_1957
country
Albania     1601.056136     1942.284244
Austria     6137.076492     8842.598030
         gdpPercap_1952  gdpPercap_1957  gdpPercap_1962
country
Albania     1601.056136     1942.284244     2312.888958
Austria     6137.076492     8842.598030    10750.721110
Belgium     8343.105127     9714.960623    10991.206760

In [49]:
## DataFrames Excercise 3
# Improve the following code with comments and better variable names

first = pd.read_csv('data/gapminder_all.csv', index_col='country')
first.head()

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,...,pop_1962,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007
country,,,,,,,,,,,,,,,,,,,,,
Algeria,Africa,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,...,11000948.0,12760499.0,14760787.0,17152804.0,20033753.0,23254956.0,26298373.0,29072015.0,31287142,33333216
Angola,Africa,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,...,4826015.0,5247469.0,5894858.0,6162675.0,7016384.0,7874230.0,8735988.0,9875024.0,10866106,12420476
Benin,Africa,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,1191.207681,...,2151895.0,2427334.0,2761407.0,3168267.0,3641603.0,4243788.0,4981671.0,6066080.0,7026113,8078314
Botswana,Africa,851.241141,918.232535,983.653976,1214.709294,2263.611114,3214.857818,4551.142150,6205.883850,7954.111645,...,512764.0,553541.0,619351.0,781472.0,970347.0,1151184.0,1342614.0,1536536.0,1630347,1639131
Burkina Faso,Africa,543.255241,617.183465,722.512021,794.826560,854.735976,743.387037,807.198586,912.063142,931.752773,...,4919632.0,5127935.0,5433886.0,5889574.0,6634596.0,7586551.0,8878303.0,10352843.0,12251209,14326203

In [50]:
second = first[first['continent'] == 'Americas']
second

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,...,pop_1962,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007
country,,,,,,,,,,,,,,,,,,,,,
Argentina,Americas,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,...,21283783.0,22934225.0,24779799.0,26983828.0,29341374.0,31620918.0,33958947.0,36203463.0,38331121,40301927
Bolivia,Americas,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,...,3593918.0,4040665.0,4565872.0,5079716.0,5642224.0,6156369.0,6893451.0,7693188.0,8445134,9119152
Brazil,Americas,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,...,76039390.0,88049823.0,100840058.0,114313951.0,128962939.0,142938076.0,155975974.0,168546719.0,179914212,190010647
Canada,Americas,11367.161120,12489.950060,13462.485550,16076.588030,18970.570860,22090.883060,22898.792140,26626.515030,26342.884260,...,18985849.0,20819767.0,22284500.0,23796400.0,25201900.0,26549700.0,28523502.0,30305843.0,31902268,33390141
Chile,Americas,3939.978789,4315.622723,4519.094331,5106.654313,5494.024437,4756.763836,5095.665738,5547.063754,7596.125964,...,7961258.0,8858908.0,9717524.0,10599793.0,11487112.0,12463354.0,13572994.0,14599929.0,15497046,16284741
Colombia,Americas,2144.115096,2323.805581,2492.351109,2678.729839,3264.660041,3815.807870,4397.575659,4903.219100,5444.648617,...,17009885.0,19764027.0,22542890.0,25094412.0,27764644.0,30964245.0,34202721.0,37657830.0,41008227,44227550
Costa Rica,Americas,2627.009471,2990.010802,3460.937025,4161.727834,5118.146939,5926.876967,5262.734751,5629.915318,6160.416317,...,1345187.0,1588717.0,1834796.0,2108457.0,2424367.0,2799811.0,3173216.0,3518107.0,3834934,4133884
Cuba,Americas,5586.538780,6092.174359,5180.755910,5690.268015,5305.445256,6380.494966,7316.918107,7532.924763,5592.843963,...,7254373.0,8139332.0,8831348.0,9537988.0,9789224.0,10239839.0,10723260.0,10983007.0,11226999,11416987
Dominican Republic,Americas,1397.717137,1544.402995,1662.137359,1653.723003,2189.874499,2681.988900,2861.092386,2899.842175,3044.214214,...,3453434.0,4049146.0,4671329.0,5302800.0,5968349.0,6655297.0,7351181.0,7992357.0,8650322,9319622
Ecuador,Americas,3522.110717,3780.546651,4086.114078,4579.074215,5280.994710,6679.623260,7213.791267,6481.776993,7103.702595,...,4681707.0,5432424.0,6298651.0,7278866.0,8365850.0,9545158.0,10748394.0,11911819.0,12921234,13755680
El Salvador,Americas,3048.302900,3421.523218,3776.803627,4358.595393,4520.246008,5138.922374,4098.344175,4140.442097,4444.231700,...,2747687.0,3232927.0,3790903.0,4282586.0,4474873.0,4842194.0,5274649.0,5783439.0,6353681,6939688
Guatemala,Americas,2428.237769,2617.155967,2750.364446,3242.531147,4031.408271,4879.992748,4820.494790,4246.485974,4439.450840,...,4208858.0,4690773.0,5149581.0,5703430.0,6395630.0,7326406.0,8486949.0,9803875.0,11178650,12572928
Haiti,Americas,1840.366939,1726.887882,1796.589032,1452.057666,1654.456946,1874.298931,2011.159549,1823.015995,1456.309517,...,3880130.0,4318137.0,4698301.0,4908554.0,5198399.0,5756203.0,6326682.0,6913545.0,7607651,8502814
Honduras,Americas,2194.926204,2220.487682,2291.156835,2538.269358,2529.842345,3203.208066,3121.760794,3023.096699,3081.694603,...,2090162.0,2500689.0,2965146.0,3055235.0,3669448.0,4372203.0,5077347.0,5867957.0,6677328,7483763
Jamaica,Americas,2898.530881,4756.525781,5246.107524,6124.703451,7433.889293,6650.195573,6068.051350,6351.237495,7404.923685,...,1665128.0,1861096.0,1997616.0,2156814.0,2298309.0,2326606.0,2378618.0,2531311.0,2664659,2780132
Mexico,Americas,3478.125529,4131.546641,4581.609385,5754.733883,6809.406690,7674.929108,9611.147541,8688.156003,9472.384295,...,41121485.0,47995559.0,55984294.0,63759976.0,71640904.0,80122492.0,88111030.0,95895146.0,102479927,108700891
Nicaragua,Americas,3112.363948,3457.415947,3634.364406,4643.393534,4688.593267,5486.371089,3470.338156,2955.984375,2170.151724,...,1590597.0,1865490.0,2182908.0,2554598.0,2979423.0,3344353.0,4017939.0,4609572.0,5146848,5675356
Panama,Americas,2480.380334,2961.800905,3536.540301,4421.009084,5364.249663,5351.912144,7009.601598,7034.779161,6618.743050,...,1215725.0,1405486.0,1616384.0,1839782.0,2036305.0,2253639.0,2484997.0,2734531.0,2990875,3242173
Paraguay,Americas,1952.308701,2046.154706,2148.027146,2299.376311,2523.337977,3248.373311,4258.503604,3998.875695,4196.411078,...,2009813.0,2287985.0,2614104.0,2984494.0,3366439.0,3886512.0,4483945.0,5154123.0,5884491,6667147
Peru,Americas,3758.523437,4245.256698,4957.037982,5788.093330,5937.827283,6281.290855,6434.501797,6360.943444,4446.380924,...,10516500.0,12132200.0,13954700.0,15990099.0,18125129.0,20195924.0,22430449.0,24748122.0,26769436,28674757
Puerto Rico,Americas,3081.959785,3907.156189,5108.344630,6929.277714,9123.041742,9770.524921,10330.989150,12281.341910,14641.587110,...,2448046.0,2648961.0,2847132.0,3080828.0,3279001.0,3444468.0,3585176.0,3759430.0,3859606,3942491
Trinidad and Tobago,Americas,3023.271928,4100.393400,4997.523971,5621.368472,6619.551419,7899.554209,9119.528607,7388.597823,7370.990932,...,887498.0,960155.0,975199.0,1039009.0,1116479.0,1191336.0,1183669.0,1138101.0,1101832,1056608
United States,Americas,13990.482080,14847.127120,16173.145860,19530.365570,21806.035940,24072.632130,25009.559140,29884.350410,32003.932240,...,186538000.0,198712000.0,209896000.0,220239000.0,232187835.0,242803533.0,256894189.0,272911760.0,287675526,301139947
Uruguay,Americas,5716.766744,6150.772969,5603.357717,5444.619620,5703.408898,6504.339663,6920.223051,7452.398969,8137.004775,...,2598466.0,2748579.0,2829526.0,2873520.0,2953997.0,3045153.0,3149262.0,3262838.0,3363085,3447496
Venezuela,Americas,7689.799761,9802.466526,8422.974165,9541.474188,10505.259660,13143.950950,11152.410110,9883.584648,10733.926310,...,8143375.0,9709552.0,11515649.0,13503563.0,15620766.0,17910182.0,20265563.0,22374398.0,24287670,26084662

In [51]:
third = second.drop('Puerto Rico')
third

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,...,pop_1962,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007
country,,,,,,,,,,,,,,,,,,,,,
Argentina,Americas,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,...,21283783.0,22934225.0,24779799.0,26983828.0,29341374.0,31620918.0,33958947.0,36203463.0,38331121,40301927
Bolivia,Americas,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,...,3593918.0,4040665.0,4565872.0,5079716.0,5642224.0,6156369.0,6893451.0,7693188.0,8445134,9119152
Brazil,Americas,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,...,76039390.0,88049823.0,100840058.0,114313951.0,128962939.0,142938076.0,155975974.0,168546719.0,179914212,190010647
Canada,Americas,11367.161120,12489.950060,13462.485550,16076.588030,18970.570860,22090.883060,22898.792140,26626.515030,26342.884260,...,18985849.0,20819767.0,22284500.0,23796400.0,25201900.0,26549700.0,28523502.0,30305843.0,31902268,33390141
Chile,Americas,3939.978789,4315.622723,4519.094331,5106.654313,5494.024437,4756.763836,5095.665738,5547.063754,7596.125964,...,7961258.0,8858908.0,9717524.0,10599793.0,11487112.0,12463354.0,13572994.0,14599929.0,15497046,16284741
Colombia,Americas,2144.115096,2323.805581,2492.351109,2678.729839,3264.660041,3815.807870,4397.575659,4903.219100,5444.648617,...,17009885.0,19764027.0,22542890.0,25094412.0,27764644.0,30964245.0,34202721.0,37657830.0,41008227,44227550
Costa Rica,Americas,2627.009471,2990.010802,3460.937025,4161.727834,5118.146939,5926.876967,5262.734751,5629.915318,6160.416317,...,1345187.0,1588717.0,1834796.0,2108457.0,2424367.0,2799811.0,3173216.0,3518107.0,3834934,4133884
Cuba,Americas,5586.538780,6092.174359,5180.755910,5690.268015,5305.445256,6380.494966,7316.918107,7532.924763,5592.843963,...,7254373.0,8139332.0,8831348.0,9537988.0,9789224.0,10239839.0,10723260.0,10983007.0,11226999,11416987
Dominican Republic,Americas,1397.717137,1544.402995,1662.137359,1653.723003,2189.874499,2681.988900,2861.092386,2899.842175,3044.214214,...,3453434.0,4049146.0,4671329.0,5302800.0,5968349.0,6655297.0,7351181.0,7992357.0,8650322,9319622
Ecuador,Americas,3522.110717,3780.546651,4086.114078,4579.074215,5280.994710,6679.623260,7213.791267,6481.776993,7103.702595,...,4681707.0,5432424.0,6298651.0,7278866.0,8365850.0,9545158.0,10748394.0,11911819.0,12921234,13755680
El Salvador,Americas,3048.302900,3421.523218,3776.803627,4358.595393,4520.246008,5138.922374,4098.344175,4140.442097,4444.231700,...,2747687.0,3232927.0,3790903.0,4282586.0,4474873.0,4842194.0,5274649.0,5783439.0,6353681,6939688
Guatemala,Americas,2428.237769,2617.155967,2750.364446,3242.531147,4031.408271,4879.992748,4820.494790,4246.485974,4439.450840,...,4208858.0,4690773.0,5149581.0,5703430.0,6395630.0,7326406.0,8486949.0,9803875.0,11178650,12572928
Haiti,Americas,1840.366939,1726.887882,1796.589032,1452.057666,1654.456946,1874.298931,2011.159549,1823.015995,1456.309517,...,3880130.0,4318137.0,4698301.0,4908554.0,5198399.0,5756203.0,6326682.0,6913545.0,7607651,8502814
Honduras,Americas,2194.926204,2220.487682,2291.156835,2538.269358,2529.842345,3203.208066,3121.760794,3023.096699,3081.694603,...,2090162.0,2500689.0,2965146.0,3055235.0,3669448.0,4372203.0,5077347.0,5867957.0,6677328,7483763
Jamaica,Americas,2898.530881,4756.525781,5246.107524,6124.703451,7433.889293,6650.195573,6068.051350,6351.237495,7404.923685,...,1665128.0,1861096.0,1997616.0,2156814.0,2298309.0,2326606.0,2378618.0,2531311.0,2664659,2780132
Mexico,Americas,3478.125529,4131.546641,4581.609385,5754.733883,6809.406690,7674.929108,9611.147541,8688.156003,9472.384295,...,41121485.0,47995559.0,55984294.0,63759976.0,71640904.0,80122492.0,88111030.0,95895146.0,102479927,108700891
Nicaragua,Americas,3112.363948,3457.415947,3634.364406,4643.393534,4688.593267,5486.371089,3470.338156,2955.984375,2170.151724,...,1590597.0,1865490.0,2182908.0,2554598.0,2979423.0,3344353.0,4017939.0,4609572.0,5146848,5675356
Panama,Americas,2480.380334,2961.800905,3536.540301,4421.009084,5364.249663,5351.912144,7009.601598,7034.779161,6618.743050,...,1215725.0,1405486.0,1616384.0,1839782.0,2036305.0,2253639.0,2484997.0,2734531.0,2990875,3242173
Paraguay,Americas,1952.308701,2046.154706,2148.027146,2299.376311,2523.337977,3248.373311,4258.503604,3998.875695,4196.411078,...,2009813.0,2287985.0,2614104.0,2984494.0,3366439.0,3886512.0,4483945.0,5154123.0,5884491,6667147
Peru,Americas,3758.523437,4245.256698,4957.037982,5788.093330,5937.827283,6281.290855,6434.501797,6360.943444,4446.380924,...,10516500.0,12132200.0,13954700.0,15990099.0,18125129.0,20195924.0,22430449.0,24748122.0,26769436,28674757
Trinidad and Tobago,Americas,3023.271928,4100.393400,4997.523971,5621.368472,6619.551419,7899.554209,9119.528607,7388.597823,7370.990932,...,887498.0,960155.0,975199.0,1039009.0,1116479.0,1191336.0,1183669.0,1138101.0,1101832,1056608
United States,Americas,13990.482080,14847.127120,16173.145860,19530.365570,21806.035940,24072.632130,25009.559140,29884.350410,32003.932240,...,186538000.0,198712000.0,209896000.0,220239000.0,232187835.0,242803533.0,256894189.0,272911760.0,287675526,301139947
Uruguay,Americas,5716.766744,6150.772969,5603.357717,5444.619620,5703.408898,6504.339663,6920.223051,7452.398969,8137.004775,...,2598466.0,2748579.0,2829526.0,2873520.0,2953997.0,3045153.0,3149262.0,3262838.0,3363085,3447496
Venezuela,Americas,7689.799761,9802.466526,8422.974165,9541.474188,10505.259660,13143.950950,11152.410110,9883.584648,10733.926310,...,8143375.0,9709552.0,11515649.0,13503563.0,15620766.0,17910182.0,20265563.0,22374398.0,24287670,26084662

In [52]:
fourth = third.drop('continent', axis = 1)
fourth.head()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,...,pop_1962,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007
country,,,,,,,,,,,,,,,,,,,,,
Argentina,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,10967.281950,...,21283783.0,22934225.0,24779799.0,26983828.0,29341374.0,31620918.0,33958947.0,36203463.0,38331121,40301927
Bolivia,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,3326.143191,...,3593918.0,4040665.0,4565872.0,5079716.0,5642224.0,6156369.0,6893451.0,7693188.0,8445134,9119152
Brazil,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,7957.980824,...,76039390.0,88049823.0,100840058.0,114313951.0,128962939.0,142938076.0,155975974.0,168546719.0,179914212,190010647
Canada,11367.161120,12489.950060,13462.485550,16076.588030,18970.570860,22090.883060,22898.792140,26626.515030,26342.884260,28954.925890,...,18985849.0,20819767.0,22284500.0,23796400.0,25201900.0,26549700.0,28523502.0,30305843.0,31902268,33390141
Chile,3939.978789,4315.622723,4519.094331,5106.654313,5494.024437,4756.763836,5095.665738,5547.063754,7596.125964,10118.053180,...,7961258.0,8858908.0,9717524.0,10599793.0,11487112.0,12463354.0,13572994.0,14599929.0,15497046,16284741

In [53]:
fourth.to_csv('result.csv')

# bonus: is your current working directory the best place to save processed data?

In [56]:
check_result = pd.read_csv('result.csv')
check_result.head()

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,...,pop_1962,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007
0,Argentina,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,...,21283783.0,22934225.0,24779799.0,26983828.0,29341374.0,31620918.0,33958947.0,36203463.0,38331121,40301927
1,Bolivia,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,...,3593918.0,4040665.0,4565872.0,5079716.0,5642224.0,6156369.0,6893451.0,7693188.0,8445134,9119152
2,Brazil,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,...,76039390.0,88049823.0,100840058.0,114313951.0,128962939.0,142938076.0,155975974.0,168546719.0,179914212,190010647
3,Canada,11367.161120,12489.950060,13462.485550,16076.588030,18970.570860,22090.883060,22898.792140,26626.515030,26342.884260,...,18985849.0,20819767.0,22284500.0,23796400.0,25201900.0,26549700.0,28523502.0,30305843.0,31902268,33390141
4,Chile,3939.978789,4315.622723,4519.094331,5106.654313,5494.024437,4756.763836,5095.665738,5547.063754,7596.125964,...,7961258.0,8858908.0,9717524.0,10599793.0,11487112.0,12463354.0,13572994.0,14599929.0,15497046,16284741

In [ ]:
## DataFrames Excercise 4
# Add documentation to the following excerpt and make yourself some notes about
# what `idxmin` and `idxmax` and where you would use them
data = pandas.read_csv('data/gapminder_gdp_europe.csv', index_col='country')
print(data.idxmin())
print(data.idxmax())

In [ ]:
## DataFrames Excercise 5

#Generate the following stats as

# GDP per capita for all countries in 1982.
# GDP per capita for Denmark for all years.
# GDP per capita for all countries for years after 1985.
# GDP per capita for each country in 2007 as a multiple of GDP per capita for
#   that country in 1952.